### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by ir0n1e** [Dahlgren/node-playwithsix#11]
Get following error with this command:
'~/node_modules/playwithsix/bin/playwithsix install @ebu_c130'

TypeError: undefined is not a function
    at /home/six3d/node_modules/playwithsix/src/pws.js:93:7
    at /home/six3d/node_modules/playwithsix/src/pws.js:23:7
    at /home/six3d/node_modules/playwithsix/node_modules/async/lib/async.js:592:17
    at done (/home/six3d/node_modules/playwithsix/node_modules/async/lib/async.js:135:19)
    at /home/six3d/node_modules/playwithsix/node_modules/async/lib/async.js:32:16
    at /home/six3d/node_modules/playwithsix/node_modules/async/lib/async.js:589:21
    at /home/six3d/node_modules/playwithsix/src/pws.js:47:7
    at Request._callback (/home/six3d/node_modules/playwithsix/src/api.js:10:9)
    at Request.self.callback (/home/six3d/node_modules/playwithsix/node_modules/request/request.js:344:22)
    at Request.EventEmitter.emit (events.js:98:17)

And following with this:
'~/node_modules/playwithsix/bin/playwithsix outdated'
[Error: Unable to fetch metadata, please try again]

**Comment by Dahlgren** [comment]
Thanks for the report! I've noticed that the mirror I was using went down yesterday. I'll fix this crash with a slightly better error :)

I'm working on the mirror issue and I hope I will have a release out in a few hours!

**Comment by Dahlgren** [comment]
Version with this issue fixed has been published to npm as 0.0.10
