### ISSUE TITLE
Feature Request: Allow for concurrent download of mods from PwS Network

### ISSUE THREAD

**Issue by SGTGunner** [Dahlgren/node-playwithsix#25]
This is a low pri feature request. As you can download a mod today.

However, allowing for concurrent mod downloads would reduce the amount of time to keep a local mod repo up to date and or when first building it out.

**Current behavior:** The download button is disable on any mods after a download of a mod is started.
**Requested behavior:** That any mod can be downloaded if a mod is already downloading.

Open Issue: limit the amount of mod that can be downloaded at any one time? PwS may have some throttling built in, but not sure.

**Comment by Dahlgren** [comment]
This is more of an inconsistency issue since mods could share dependencies and start downloading the same files at once

The underlying library could of course be improved to better handling concurrent downloads :)

**Comment by Dahlgren** [comment]
I guess this ticket is related to the Arma3Sync Admin repository?

**Comment by Dahlgren** [comment]
I guess this is supposed to be on the Arma3Sync Manager project.

The PwS library downloads files concurrently, currently based on the number of cores available due to hashing and other operations.

The concurrent download of mods in the manager is disabled due to mods possibly having the same dependencies. If two mods decide to download the same dependency at once resulting in duplicated IO and possibly even downloading the same files at once.

I guess this could be better abstracted in this library to allow the manager for more concurrency.

**Comment by WSIContractor** [comment]
okay. I understand it from a concurrency point of view that it could be difficult based on the dependencies. If you select a mod to download and it starts to download, does the node-playwithsix know what the request is and if the request is already know then I get blocking that mod and it dependencies from downloading.

I think difficulty might be two different mods with a reliance on the same dependent mod how do know or prevent a circular dependency from happening?

**Comment by Dahlgren** [comment]
When a mod is selected for download all dependencies are calculated and circular dependencies are removed. The list of mods are processed one by one until they are done. Files per mod is downloaded concurrently. If two mods are selected for download independently (i.e. two download buttons are pressed in the manager) then two lists of needed mods are created and downloaded independently. This can cause collisions where the same mod is downloaded twice at once. The same think would happen if the download button for a mod is pressed twice in the search results for example. This is why those are blocked too :)

A better solution would be to have a global queue of all download jobs and use that as a bag of tasks that are processed as needed to avoid downloading the same mod concurrently by two different jobs. I guess it's doable but the library would need a major rewrite.

**Comment by Dahlgren** [comment]
withSIX has been shutdown
